### ISSUE TITLE
NodeSchool at Node.js Interactive text

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#28]
Final description + programme needs to go out to Tracy. @stefanmirck

**Comment by stefanmirck** [comment]
# Node.js Interactive Europe x NodeSchool

We're excited to bring NodeSchool to Node.js Interactive Europe! NodeSchool is a community-driven effort with hundreds of local chapters throughout the world that aim to teach essential programming skills. NodeSchool organizes in-person workshops and builds on an open source curriculum that teaches various Node.js and JavaScript skills in an interactive, self-guided format.

Join your fellow attendees in one of the sessions and have the friendly organizers of NodeSchool Amsterdam and other members of the NodeSchool and Node.js communities help you through the sessions. There are many workshoppers (open source lesson modules) available for many skill levels — this instance we'll be focussing on some in-depth JavaScript and Node.js topics. 

In order to participate you'll need to bring your own laptop. This session of NodeSchool will include
these workshoppers: 

- `planet-proto`: Understanding JavaScript Prototypes.
- `going-native`: An exploration of Node.js from the underside: native C++ add-ons.
- `stream-adventure`: Learn to compose streaming interfaces.
- `bacon-love`: Learn concepts of Functional and Reactive Programming using Bacon.js.
- (`lololodash`: Learn Lo-Dash to handle your arrays and objects simple.)
- (`how-to-npm`: Learn how to use and create npm modules.)

For more information about NodeSchool and its community, visit: [nodeschool.io](http://nodeschool.io/).
